### ISSUE TITLE
FYI: Pandas and numpy warnings on final 3 tests of clean install of tax-microdata-benchmarking as of PR 134

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#135]
FYI. On clean install of tax-microdata-benchmarking as of PR 134:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/0cbb929c-375c-47d3-a2fe-58d1a6ee1915)

I get several pandas and numpy warnings. I am not sure if new code, or older code, is triggering these warnings, but I don't recall seeing them before:

- FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
- SettingWithCopyWarning:  A value is trying to be set on a copy of a slice from a DataFrame
- PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.
- DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
  Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)

Examples below:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/763f1b1c-0319-413b-b13b-96bb1c3caca6)

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/a3919ab9-3f92-4934-9c98-146788e40d81)

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/ab77abe3-32d8-42b4-b939-ada0cad8898e)

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/1b516b7d-d339-4719-8bc4-42a4a22230c0)

**Comment by martinholmer** [comment]
@nikhilwoodruff,  All the remaining warnings are in code you wrote.
What is your timeline for eliminating these warnings?

**Comment by martinholmer** [comment]
After the merge of PR #178, we have these warnings when activating the usually skipped `test_create_file` test:

============================ warnings summary ============================
tests/test_create_tmd_variables.py::test_create_file
.../site-packages/**policyengine_core/enums/enum.py**: 56: 
**FutureWarning**: `Series.__getitem__` treating keys as positions is deprecated.
In a future version, integer keys will always be treated as labels (consistent with
DataFrame behavior).  To access a value by position, use `ser.iloc[pos]`
`        if isinstance(array[0], Enum):`

tests/test_create_tmd_variables.py: **458 warnings**
.../**tmd/utils/reweight.py**: 176: 
**PerformanceWarning**: DataFrame is highly fragmented.  
This is usually the result of calling `frame.insert` many times, which has poor performance. 
Consider joining all columns at once using `pd.concat(axis=1)` instead. 
To get a de-fragmented frame, use `newframe = frame.copy()`
 `        loss_matrix[label] = mask * values`

The first warning was reported in a [`policyengine-core` issue](https://github.com/PolicyEngine/policyengine-core/issues/238) some time ago, but it has not yet been fixed.

The second warning is from the `tmd/utils/reweight.py` module that uses a fairly convoluted process of building the `loss_matrix`.   This second warning is saying the convoluted code generates a "highly fragmented" data structure that has "poor performance".

All the other warning originally reported in this issue have been fixed by code improvements merged during August 2024.

**Comment by donboyd5** [comment]
Thank you @Martin Holmer ***@***.***>
