### ISSUE TITLE
Add planning of Phase 2

### ISSUE THREAD

**Issue by nikhilwoodruff** [PSLmodels/tax-microdata-benchmarking#15]
... to the planning document.

**Comment by donboyd5** [comment]
**Thoughts on initial priorities for Phase 2**

With slight editing, this reprises an email I sent to @nikhilwoodruff and @martinholmer on Mar 6, 2024.

Here are some thoughts on initial Phase 2 priorities:

- Identify variables we need to add to the puf or modify significantly - probably Nikhil primarily, with reaction from Martin and Don
- Identify subset of those variables that are crucial to evaluating TCJA provisions scheduled to sunset that are likely to be of great policy/political interest. Maybe a table like the one below would be useful. Presumably Nikhil would be lead on this, too.
- Methodology for distinguishing filers from nonfilers so that we can target filers as well as target the universe. Here are two prior discussions on this topic: [#1](https://github.com/PSLmodels/taxdata/issues/366) and [#2](https://github.com/PSLmodels/Tax-Calculator/issues/2501). My best python code for identifying filers in the puf is in #2, [here](https://github.com/PSLmodels/Tax-Calculator/issues/2501#issuecomment-726694109). It's possible that I progressed beyond this, but I'll have to look; I know I was pretty satisfied with the definition just linked to. I can summarize in a GitHub issue if useful. Presumably this code should also work well (I hope) on the PE flat file since it has puf variables. Is what I've provided sufficient? Should we start with that and open a GitHub issue to address questions that inevitably will pop up?
- Identify filers and non filers in the PE flat file. Set aside nonfilers as we will backcast them to 2015 and use them with 2015 puf.
- Choose variables to target in 2015 and 2021:
  - Filers IRS targets
    - I've provided data on over 2000 potential targets in each year, [here as csv](https://github.com/donboyd5/taxdata-psl/tree/main/data) and [here in explorable form](https://boyd-targets-mockup.netlify.app/prepare.html#sec-show-targets), 
    - I think we should start small, focusing on variables that we know are crucial for tax liability or for TCJA-related potential sunsets (especially SALT, standard deduction, and child tax credit - related targets). Maybe # returns by broad AGI range and marital status, total AGI by same, wages by same, and capital gains by same; plus available itemized deductions by major category (medical, contributions, SALT, other) -- these will be especially challenging for 2021. This could still be over 100 targets.
  - Universe CPS targets
    - probably just a few targets especially related to CTC, by broad income range that we can compute with CPS variables
    - I'm happy to take on the task of developing CPS targets for 2015 and 2021 (summarizing CPS microdata) but would want to talk about what CPS variables we need.
- Not right away, but in month two we'll want to develop extrapolation factors and aggregate targets for post 2021, using CBO forecasts and other info as needed.
- Anyway, these are my initial thoughts. Plenty to work on in the near term.

Thoughts? Did I miss something or get something wrong?

**Comment by MaxGhenis** [comment]
I'd avoid constructing targets from the CPS itself unless necessary. More accurate population sources are available, and on some of the aggregates it might be more well-suited to than others (e.g. nonfiler income distribution) I'm skeptical of its reliability, given how much reweighting it improves accuracy on other metrics.

**Comment by donboyd5** [comment]
Thanks, @MaxGhenis. Excellent point. As we pick universe variables to target, and propose sources of data for establishing targets for those variables, as well as specific target values, would much appreciate comments on them. And if you have a link to one or more places where you've already established and documented these sources and values for selected universe variables, would much appreciate knowing.

**Comment by nikhilwoodruff** [comment]
OK- so [here's](https://docs.google.com/spreadsheets/d/1jg-YrAtAYDg61dZv8iCSZ5iaTXxUrceMJGCGGZpWyMw/edit?usp=sharing) a spreadsheet with the individual expiring TCJA provisions, with some measure of priority by their share of the total budgetary impacts. I think we can assume all the variables that are important for matching CBO TCJA impacts can be found in this?

**Comment by nikhilwoodruff** [comment]
Also adding here (plus tag of https://github.com/PSLmodels/Tax-Calculator/issues/2501)- Don, that code looks translatable and I can take a go at it. But (and correct me if this was obvious!) I'm not sure if we should use the explicit values in that code. Although [the IRS publication you linked](https://www.irs.gov/pub/irs-prior/p17--2017.pdf) gives them, [U.S.C s. 6012](https://www.law.cornell.edu/uscode/text/26/6012) ties them explicitly to policy instruments e.g. the standard deduction that are affected by TCJA reforms.

**Comment by nikhilwoodruff** [comment]
I think we can close this now as we approach the end of Phase 2.

**Comment by donboyd5** [comment]
Agreed.
