### ISSUE TITLE
Seeking help getting permissions to make a PR to tax-microdata-benchmarking

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#256]
@nikhilwoodruff @MaxGhenis 

Neither I nor @jdebacker have been successful making a PR to tax-microdata-benchmarking - we fail required permissions that seem related to @nikhilwoodruff , details in a minute. However, @martinholmer has been successful, but we're not sure what settings he might have that are different. Can you assist us, please? Details follow:

**Background, and what fails and how**

- I and @martinholmer are listed as contributors to tax-microdata-benchmarking. @jdebacker is not.
- This morning I created a simple pull request: create a branch off of current master, make a one-word change to a README, and create a PR. Here's [the PR](https://github.com/PSLmodels/tax-microdata-benchmarking/pull/254/files).
- It [fails the tests](https://github.com/PSLmodels/tax-microdata-benchmarking/actions/runs/11519376964/job/32068226196?pr=254) in `make install` -- see screenshot after this explanation.
- Here's my reconstruction of events
- `make install`
   -  python [tmd/download_prerequisites.py](https://github.com/PSLmodels/tax-microdata-benchmarking/blob/master/tmd/download_prerequisites.py)
       -   line 26 calls `download_prerequisites()`, which generates a call in line 6 to `download_gh_release_asset` in [cloud.py](https://github.com/PSLmodels/tax-microdata-benchmarking/blob/master/tmd/utils/cloud.py) to try to get the 2015 PUF with the 3 arguments you see immediatgely below
![image](https://github.com/user-attachments/assets/8cf1df25-d580-4589-ad90-126cd2e936e9)
       - however it fails and asserts at line 62 "Release tmd-prerequisites not found." (see screenshot further below)

@jdebacker encountered the same thing and may have comments to add.

I'm not sure how to fix this (I've tried many things). Can you help?

Many thanks.

**Fuller message below**

![image](https://github.com/user-attachments/assets/3251c4da-073f-4058-913f-df1ecfbacf89)

**Comment by nikhilwoodruff** [comment]
Just got to this! It looks like this is solved: the issue was that pull requests need to be from a branch, not a fork. This is unavoidable: the reason we have to do this is because of the PUF being non-public. If I didn't have access to the PUF, I could just extract it from this repo by forking, adding some Python lines to our tests of the dataset build process that contain `email_nikhil_the_puf_csv()`, wait for the tests to pass, and get an email.

**Comment by nikhilwoodruff** [comment]
This repo has to download the non-public input files from somewhere (because this repo is public, and GitHub doesn't let you have a public repo with some private data- it has to be all public or all private), and I chose a private GitHub repo because it's the most straightforward and everything else is on GitHub too. That repo is https://github.com/nikhilwoodruff/tax-microdata-benchmarking-releases. How it works is that the TMD repo has a token that lets it download the data files from the TMD-releases repo. We [generate](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) this token through the settings page on the TMD-releases repo. Feel free to change this setup with another way of downloading the private files into this repo so we can run tests of the data generation process, but this way definitely seems least complex.

I'd like to transfer the TMD-releases repo to PSLmodels though to avoid dependence on me for this- @jdebacker could I have permissions for this please?

**Comment by nikhilwoodruff** [comment]
The only further thing I'd add is that GitHub as a policy gives 404 (not found) errors even when the real issue is that a machine doesn't have authorisation to access a file, not that the file doesn't exist (this can be confusing if you're following what the error message is saying and I've tripped up on it before!). The reason for this is to avoid disclosing whether the requested unauthorised file exists.

**Comment by donboyd5** [comment]
Thanks, @nikhilwoodruff! I'll be closing this soon after I double-check to be sure I understand everything.

**Comment by donboyd5** [comment]
@martinholmer and @nikhilwoodruff straightened me out on this.

The key things to know are:

- Only project contributors can successfully initiate a PR. This is intended to protect the privacy of the PUF data.
- The PR should be made directly to upstream and not through the contributor's fork. A typical PR command would be something like: `git push upstream pr-test`
- @martinholmer says the branch name used for the PR should not already be present on the user's fork. Best to create a new branch or rename the branch and using that new name for the PR.


Note that @nikhilwoodruff says:

`I'd like to transfer the TMD-releases repo to PSLmodels though to avoid dependence on me for this- @jdebacker could I have permissions for this please?`
