### ISSUE TITLE
Tax-Calc compatibility issues with the " * 100 " scaling of weights

### ISSUE THREAD

**Issue by towashington** [PSLmodels/tax-microdata-benchmarking#285]
I noticed that, when using the TMD file in Tax-Calc, the unit of revenue estimates is a hundred dollars, instead of a dollar. After a little digging, I was wondering if it's related to [line 29](https://github.com/PSLmodels/tax-microdata-benchmarking/blob/master/tmd/create_taxcalc_sampling_weights.py#L29) here, which used to be scaled up by 100 times for compatibility in Tax-Calc, but no longer. Is that right? And if so, is it in the road map to add the 100 scaling back?

**Comment by martinholmer** [comment]
In issue #285, @towashington said:
> I noticed that, when using the TMD file in Tax-Calc, the unit of revenue estimates is a hundred dollars, instead of a dollar. After a little digging, I was wondering if it's related to [line 29](https://github.com/PSLmodels/tax-microdata-benchmarking/blob/master/tmd/create_taxcalc_sampling_weights.py#L29) here, which used to be scaled up by 100 times for compatibility in Tax-Calc, but no longer. Is that right? And if so, is it in the road map to add the 100 scaling back?

Thanks for your questions.

Yes, since PR #264 was merged about two weeks ago, the TMD weights are being handled differently.   The increase precision is to support subnational area weights.   And Tax-Calculator has been revised to handle the TMD weights that are not scaled by 100.

Here is how to get up-to-date on your computer:
(1) Create a Tax-Calculator package using the most recent Tax-Calculator source code.
(2) Create the three `tmd_*` data files using the most recent TMD source code.

Step (1) involves executing these commands:
```
Tax-Calculator% conda activate taxcalc-dev
(taxcalc-dev) Tax-Calculator% ./gitsync
(taxcalc-dev) Tax-Calculator% make package
```

Step (2) involves updating the `tax-microdata` source code and executing `make data` as described [here](https://github.com/PSLmodels/tax-microdata-benchmarking/tree/master?tab=readme-ov-file#tax-microdata).   On my computer the size of the three data files are:
```
-rw-r--r--  1 mrh  staff  12133178 Nov  5 14:32 tmd.csv.gz
-rw-r--r--  1 mrh  staff     12611 Oct 26 19:29 tmd_growfactors.csv
-rw-r--r--  1 mrh  staff  52609134 Nov  5 14:32 tmd_weights.csv.gz
```
As you can see, the `tmd_weights.csv.gz` file is now much larger because the unscaled weights are being stored as floats with five digits after the decimal point.

Please let us know whether or not doing these things resolves your problem.

**Comment by towashington** [comment]
Thank, Martin. I must have run the model after the latest tmd code change but before the latest taxcalc code change. I’ll implement your suggestion and circle back if I run into any issues. Thanks again!

---------------------
Blame my phone for typos
<https://aka.ms/o0ukef>
________________________________

**Comment by martinholmer** [comment]
@towashington, Have you been able to resolve the problem you reported in TMD issue #285?

**Comment by towashington** [comment]
Just confirming that the issue is resolved with the Tax-Calc update. Thanks, @martinholmer!

**Comment by martinholmer** [comment]
@towashington said in issue #285:
> Just confirming that the issue is resolved with the Tax-Calc update.

Good to hear this!   Thanks for the feedback.
